export const SET_USER = 'SET_USER'
export const SET_USER_DATA = 'SET_USER_DATA'
export const SET_PHOTO_DATA = 'SET_PHOTO_DATA'
export const SHOW_ONLY_MY_PHOTO = 'SHOW_ONLY_MY_PHOTO'
export const ADD_PHOTO = 'ADD_PHOTO'
